spring:
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
      timeout: 1800s

  application:
    name: gateway

  mvc:
    hidden-method:
      filter:
        enabled: true

server:
  port: 8080

feign:
  httpclient:
    enabled: true

logging:
  level:
    com:
      minidooray:
        gateway:
          client: DEBUG
accounts:
  host: http://localhost:8083
tasks:
  account-host: http://localhost:8082/members
  host: http://localhost:8082